# Generated by Django 5.2.11 on 2026-02-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (рус)')),
                ('description', models.TextField(verbose_name='Описание (укр)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание (рус)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='candles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='candles/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='candles/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_hit', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (рус)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['group__order', 'group__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название группы (рус)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'Группы категорий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Технический код, например relax, gift, home.', unique=True, verbose_name='Код (латиницей)')),
                ('title_uk', models.CharField(max_length=120, verbose_name='Назва (укр)')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название (рус)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание (рус)')),
                ('description', models.TextField(blank=True, verbose_name='Опис / Описание')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Баннер коллекции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Коллекция по настроению',
                'verbose_name_plural': 'Коллекции по настроению',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('city', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('warehouse', models.CharField(blank=True, default='', max_length=200, verbose_name='Відділення Нової пошти')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Оплата карткою'), ('cod', 'Накладений платіж')], default='', max_length=10, verbose_name='Спосіб оплати')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
                ('agree_to_terms', models.BooleanField(default=False, verbose_name='Згода на обробку персональних даних')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('processing', 'В обробці'), ('sent', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candles/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.candle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='shop.candle')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_links', to='shop.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('candle', 'category')},
            },
        ),
        migrations.AddField(
            model_name='candle',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='candles', through='shop.CandleCategory', to='shop.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.categorygroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='candle',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collection', verbose_name='Коллекция по настроению'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='shop.candle', verbose_name='Свеча')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар в коллекции',
                'verbose_name_plural': 'Товары в коллекции',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('candle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.candle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Товари в замовленні',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_category_group_name_uk'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'candle'), name='uniq_collection_candle'),
        ),
    ]
