# Generated by Django 6.0.1 on 2026-02-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='shop.candle', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Группа опций товара',
                'verbose_name_plural': 'Группы опций товаров',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная')),
                ('input_type', models.CharField(choices=[('select', 'Выпадающий список'), ('radio', 'Радио-кнопки'), ('buttons', 'Кнопки')], default='select', max_length=10, verbose_name='Тип ввода')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.productoptiongroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Опция товара',
                'verbose_name_plural': 'Опции товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('value_name', models.CharField(max_length=100, verbose_name='Выбранное значение')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Изменение цены')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='shop.orderitem', verbose_name='Позиция заказа')),
                ('option_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productoptiongroup', verbose_name='Группа опций')),
            ],
            options={
                'verbose_name': 'Выбранная опция',
                'verbose_name_plural': 'Выбранные опции',
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Изменение цены (+/-)')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.productoption', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Значение опции',
                'verbose_name_plural': 'Значения опций',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
