# Generated by Django 5.2.11 on 2026-02-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productoptiongroup_productoption_orderitemoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemoption',
            name='option_group',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Опция товара', 'verbose_name_plural': 'Опции товара'},
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.candle', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='ProductOptionGroup',
        ),
    ]
