# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderitemoption_option_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'name')},
        ),
    ]
