# Generated by Django 5.2.11 on 2026-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productoption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название опции (рус)'),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='value_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Значение (рус)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название опции (укр)'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение (укр)'),
        ),
    ]
