# Generated by Django 5.2.11 on 2026-02-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productoption_name_ru_productoptionvalue_value_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
