# Generated by Django 5.2.11 on 2026-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productoptionvalue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аромата (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название аромата (рус)')),
                ('description', models.TextField(blank=True, verbose_name='Описание аромата (укр)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание аромата (рус)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scents/', verbose_name='Картинка аромата')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Аромат',
                'verbose_name_plural': 'Ароматы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
