# Generated by Django 5.2.11 on 2026-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_home_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['-is_active', 'order', '-updated_at', '-id'], 'verbose_name': 'Баннер главной страницы', 'verbose_name_plural': 'Баннер главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='scentcategory',
            options={'ordering': ['group__order', 'group__name', 'order', 'name'], 'verbose_name': 'Категория аромата', 'verbose_name_plural': 'Ароматы категории'},
        ),
        migrations.AddField(
            model_name='homebanner',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=4, verbose_name='Время показа (сек)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
