# Generated by Django 6.0.1 on 2026-02-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_collection_bilingual_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candles/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.candle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
