# Generated by Django 6.0.1 on 2026-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_candleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='candles/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='candle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='candles/', verbose_name='Фото 3'),
        ),
    ]
