# Generated by Django 6.0.1 on 2026-02-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_categorygroup_and_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Баннер коллекции'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='shop.candle', verbose_name='Свеча')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар в коллекции',
                'verbose_name_plural': 'Товары в коллекции',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'candle'), name='uniq_collection_candle')],
            },
        ),
    ]
