# Generated by Django 6.0.1 on 2026-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_collection_banner_collectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner_desktop',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1200×400px', null=True, upload_to='collections/', verbose_name='Баннер коллекции (десктоп)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='banner_mobile',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 768×300px', null=True, upload_to='collections/', verbose_name='Баннер коллекции (мобильный)'),
        ),
    ]
