# Generated by Django 6.0.1 on 2026-02-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_collection_banner_desktop_collection_banner_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='banner_desktop',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='banner_mobile',
        ),
    ]
